contentDir = "content"
baseURL = "https://elisablog.netlify.com"
layoutDir = "layouts"
publishDir = "public"
buildDrafts = false
canonifyURLs = true
title = "Amiga Eli"
theme = "hugo-theme-bootstrap4-blog"

[taxonomies]
  category = "categories"
  tag = "tags"
