contentDir = "content"
baseURL = "https://elisablog.netlify.com"
layoutDir = "layouts"
publishDir = "public"
buildDrafts = false
canonifyURLs = true
title = "Amiga Eli"
# theme to use (located by default in /themes/THEMENAME/)
themesDir = "themes"
theme = "hugo-theme-bootstrap4-blog"

[taxonomies]
  category = "categories"
  tag = "tags"
