# Global settings applied to the whole site.
[build]
  publish = "public/"
  themesDir = "themes"
  theme = "hugo-theme-bootstrap4-blog"
  command = "hugo -t hugo-theme-bootstrap4-blog & hugo"

# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
  command = "hugo"
  [context.production.environment]
    HUGO_VERSION = "0.24.1"

# Deploy Preview context: All Deploy Previews
# will inherit these settings.
[context.deploy-preview.environment]
  HUGO_VERSION = "0.24.1"

# Branch Deploy context: All deploys that are not in
# an active Deploy Preview will inherit these settings.
[context.branch-deploy]
  command = "hugo"

# Specific branch context: Deploys from this branch
# will take these settings and override their
# current ones.
[context.feature]
  command = "hugo"

[context."features/branch"]
  command = "hugo"
